// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Bidder        int64                  `protobuf:"varint,3,opt,name=bidder,proto3" json:"bidder,omitempty"`
	BidAmount     int64                  `protobuf:"varint,4,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAmount) Reset() {
	*x = BidAmount{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAmount) ProtoMessage() {}

func (x *BidAmount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAmount.ProtoReflect.Descriptor instead.
func (*BidAmount) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidAmount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BidAmount) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidAmount) GetBidder() int64 {
	if x != nil {
		return x.Bidder
	}
	return 0
}

func (x *BidAmount) GetBidAmount() int64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

type BidAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Used if auction is not running
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAck) Reset() {
	*x = BidAck{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAck) ProtoMessage() {}

func (x *BidAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAck.ProtoReflect.Descriptor instead.
func (*BidAck) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BidAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AuctionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int64                  `protobuf:"varint,1,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	HighestBidder int64                  `protobuf:"varint,2,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	AuctionOver   bool                   `protobuf:"varint,3,opt,name=auction_over,json=auctionOver,proto3" json:"auction_over,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionResult) Reset() {
	*x = AuctionResult{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionResult) ProtoMessage() {}

func (x *AuctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionResult.ProtoReflect.Descriptor instead.
func (*AuctionResult) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionResult) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *AuctionResult) GetHighestBidder() int64 {
	if x != nil {
		return x.HighestBidder
	}
	return 0
}

func (x *AuctionResult) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

func (x *AuctionResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

type ReplicaConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          int64                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaConnection) Reset() {
	*x = ReplicaConnection{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaConnection) ProtoMessage() {}

func (x *ReplicaConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaConnection.ProtoReflect.Descriptor instead.
func (*ReplicaConnection) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaConnection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplicaConnection) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ReplicaUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HighestBidder     int64                  `protobuf:"varint,2,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	HighestBid        int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	AuctionFinished   bool                   `protobuf:"varint,4,opt,name=auction_finished,json=auctionFinished,proto3" json:"auction_finished,omitempty"`
	RequestIdentifier int64                  `protobuf:"varint,5,opt,name=request_identifier,json=requestIdentifier,proto3" json:"request_identifier,omitempty"`
	Response          *BidAck                `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplicaUpdate) Reset() {
	*x = ReplicaUpdate{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaUpdate) ProtoMessage() {}

func (x *ReplicaUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaUpdate.ProtoReflect.Descriptor instead.
func (*ReplicaUpdate) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicaUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReplicaUpdate) GetHighestBidder() int64 {
	if x != nil {
		return x.HighestBidder
	}
	return 0
}

func (x *ReplicaUpdate) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicaUpdate) GetAuctionFinished() bool {
	if x != nil {
		return x.AuctionFinished
	}
	return false
}

func (x *ReplicaUpdate) GetRequestIdentifier() int64 {
	if x != nil {
		return x.RequestIdentifier
	}
	return 0
}

func (x *ReplicaUpdate) GetResponse() *BidAck {
	if x != nil {
		return x.Response
	}
	return nil
}

type ReplicaIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaIdentity) Reset() {
	*x = ReplicaIdentity{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaIdentity) ProtoMessage() {}

func (x *ReplicaIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaIdentity.ProtoReflect.Descriptor instead.
func (*ReplicaIdentity) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicaIdentity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplicaIdentity) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReplicaState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identity        *ReplicaIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Replicas        []*ReplicaConnection   `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	HighestBidder   int64                  `protobuf:"varint,3,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	HighestBid      int64                  `protobuf:"varint,4,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	AuctionFinished bool                   `protobuf:"varint,5,opt,name=auction_finished,json=auctionFinished,proto3" json:"auction_finished,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicaState) Reset() {
	*x = ReplicaState{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaState) ProtoMessage() {}

func (x *ReplicaState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaState.ProtoReflect.Descriptor instead.
func (*ReplicaState) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicaState) GetIdentity() *ReplicaIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ReplicaState) GetReplicas() []*ReplicaConnection {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *ReplicaState) GetHighestBidder() int64 {
	if x != nil {
		return x.HighestBidder
	}
	return 0
}

func (x *ReplicaState) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicaState) GetAuctionFinished() bool {
	if x != nil {
		return x.AuctionFinished
	}
	return false
}

type ElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderGreater bool                   `protobuf:"varint,1,opt,name=sender_greater,json=senderGreater,proto3" json:"sender_greater,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{8}
}

func (x *ElectionResponse) GetSenderGreater() bool {
	if x != nil {
		return x.SenderGreater
	}
	return false
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{9}
}

func (x *Id) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReplicaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      []string               `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"` // List of server URLs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaList) Reset() {
	*x = ReplicaList{}
	mi := &file_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaList) ProtoMessage() {}

func (x *ReplicaList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaList.ProtoReflect.Descriptor instead.
func (*ReplicaList) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicaList) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"p\n" +
	"\tBidAmount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06bidder\x18\x03 \x01(\x03R\x06bidder\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x04 \x01(\x03R\tbidAmount\"g\n" +
	"\x06BidAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x98\x01\n" +
	"\rAuctionResult\x12\x1f\n" +
	"\vhighest_bid\x18\x01 \x01(\x03R\n" +
	"highestBid\x12%\n" +
	"\x0ehighest_bidder\x18\x02 \x01(\x03R\rhighestBidder\x12!\n" +
	"\fauction_over\x18\x03 \x01(\bR\vauctionOver\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\a\n" +
	"\x05Empty\"7\n" +
	"\x11ReplicaConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\"\xf4\x01\n" +
	"\rReplicaUpdate\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0ehighest_bidder\x18\x02 \x01(\x03R\rhighestBidder\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12)\n" +
	"\x10auction_finished\x18\x04 \x01(\bR\x0fauctionFinished\x12-\n" +
	"\x12request_identifier\x18\x05 \x01(\x03R\x11requestIdentifier\x12#\n" +
	"\bresponse\x18\x06 \x01(\v2\a.BidAckR\bresponse\"?\n" +
	"\x0fReplicaIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xdf\x01\n" +
	"\fReplicaState\x12,\n" +
	"\bidentity\x18\x01 \x01(\v2\x10.ReplicaIdentityR\bidentity\x12.\n" +
	"\breplicas\x18\x02 \x03(\v2\x12.ReplicaConnectionR\breplicas\x12%\n" +
	"\x0ehighest_bidder\x18\x03 \x01(\x03R\rhighestBidder\x12\x1f\n" +
	"\vhighest_bid\x18\x04 \x01(\x03R\n" +
	"highestBid\x12)\n" +
	"\x10auction_finished\x18\x05 \x01(\bR\x0fauctionFinished\"9\n" +
	"\x10ElectionResponse\x12%\n" +
	"\x0esender_greater\x18\x01 \x01(\bR\rsenderGreater\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\vReplicaList\x12\x1a\n" +
	"\breplicas\x18\x01 \x03(\tR\breplicas2\xe9\x02\n" +
	"\aAuction\x12\x1a\n" +
	"\x03Bid\x12\n" +
	".BidAmount\x1a\a.BidAck\x12 \n" +
	"\x06Result\x12\x06.Empty\x1a\x0e.AuctionResult\x12\x1a\n" +
	"\vGetClientId\x12\x06.Empty\x1a\x03.Id\x12&\n" +
	"\x0eGetReplicaList\x12\x06.Empty\x1a\f.ReplicaList\x125\n" +
	"\x10ReplicaConnected\x12\x12.ReplicaConnection\x1a\r.ReplicaState\x12&\n" +
	"\rUpdateReplica\x12\r.ReplicaState\x1a\x06.Empty\x124\n" +
	"\rStartElection\x12\x10.ReplicaIdentity\x1a\x11.ElectionResponse\x12&\n" +
	"\x10ElectionFinished\x12\x03.Id\x1a\r.ReplicaState\x12\x1f\n" +
	"\rWellnessCheck\x12\x06.Empty\x1a\x06.EmptyB\x0eZ\fauction/grpcb\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_proto_goTypes = []any{
	(*BidAmount)(nil),         // 0: BidAmount
	(*BidAck)(nil),            // 1: BidAck
	(*AuctionResult)(nil),     // 2: AuctionResult
	(*Empty)(nil),             // 3: Empty
	(*ReplicaConnection)(nil), // 4: ReplicaConnection
	(*ReplicaUpdate)(nil),     // 5: ReplicaUpdate
	(*ReplicaIdentity)(nil),   // 6: ReplicaIdentity
	(*ReplicaState)(nil),      // 7: ReplicaState
	(*ElectionResponse)(nil),  // 8: ElectionResponse
	(*Id)(nil),                // 9: Id
	(*ReplicaList)(nil),       // 10: ReplicaList
}
var file_proto_proto_depIdxs = []int32{
	1,  // 0: ReplicaUpdate.response:type_name -> BidAck
	6,  // 1: ReplicaState.identity:type_name -> ReplicaIdentity
	4,  // 2: ReplicaState.replicas:type_name -> ReplicaConnection
	0,  // 3: Auction.Bid:input_type -> BidAmount
	3,  // 4: Auction.Result:input_type -> Empty
	3,  // 5: Auction.GetClientId:input_type -> Empty
	3,  // 6: Auction.GetReplicaList:input_type -> Empty
	4,  // 7: Auction.ReplicaConnected:input_type -> ReplicaConnection
	7,  // 8: Auction.UpdateReplica:input_type -> ReplicaState
	6,  // 9: Auction.StartElection:input_type -> ReplicaIdentity
	9,  // 10: Auction.ElectionFinished:input_type -> Id
	3,  // 11: Auction.WellnessCheck:input_type -> Empty
	1,  // 12: Auction.Bid:output_type -> BidAck
	2,  // 13: Auction.Result:output_type -> AuctionResult
	9,  // 14: Auction.GetClientId:output_type -> Id
	10, // 15: Auction.GetReplicaList:output_type -> ReplicaList
	7,  // 16: Auction.ReplicaConnected:output_type -> ReplicaState
	3,  // 17: Auction.UpdateReplica:output_type -> Empty
	8,  // 18: Auction.StartElection:output_type -> ElectionResponse
	7,  // 19: Auction.ElectionFinished:output_type -> ReplicaState
	3,  // 20: Auction.WellnessCheck:output_type -> Empty
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
